dist: trusty
sudo: false

language: node_js
node_js:
  - "8"
  - "10"

cache:
  directories:
    - "node_modules"

jobs:
  include:
    - stage: npm release
      script: echo skipping build script
      before_deploy: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc  
      deploy:
        on: 
          branch: master
          skip_cleanup: true
          tags: true
        provider: script
        script: npm publish --otp $(npx otp-cli totp generate -k $NPM_OTP_SECRET)
      after_deploy: rm ~/.npmrc
